# Generated by Django 2.2 on 2019-12-21 21:03

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ulanyjy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('ady', models.CharField(max_length=200)),
                ('mac_adresi', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Ulanyjylar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bolumler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Bolumler',
            },
        ),
        migrations.CreateModel(
            name='Edaralar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Edaralar',
            },
        ),
        migrations.CreateModel(
            name='Welayatlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Welayatlar',
            },
        ),
        migrations.CreateModel(
            name='Hasabat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady', models.CharField(max_length=200)),
                ('bölümi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dolanysygy.Bolumler')),
            ],
            options={
                'verbose_name_plural': 'Hasabat',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady', models.CharField(max_length=200)),
                ('dokument', models.FileField(upload_to='Dokumentler')),
                ('döredilen_senesi', models.DateTimeField(auto_now=True)),
                ('üýgedilen_senesi', models.DateTimeField(auto_now_add=True)),
                ('bölümi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dolanysygy.Bolumler')),
                ('edarasy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dolanysygy.Edaralar')),
                ('eýesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('görnüşi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dolanysygy.Hasabat')),
                ('welaýaty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dolanysygy.Welayatlar')),
            ],
            options={
                'verbose_name_plural': 'Faýl',
            },
        ),
        migrations.AddField(
            model_name='edaralar',
            name='welaýaty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dolanysygy.Welayatlar'),
        ),
        migrations.AddField(
            model_name='ulanyjy',
            name='bölümi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dolanysygy.Bolumler'),
        ),
        migrations.AddField(
            model_name='ulanyjy',
            name='edarasy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dolanysygy.Edaralar'),
        ),
        migrations.AddField(
            model_name='ulanyjy',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='ulanyjy',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='ulanyjy',
            name='welaýaty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dolanysygy.Welayatlar'),
        ),
    ]
