# Generated by Django 2.1 on 2019-12-20 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dolanysygy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolumler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Bolumler',
            },
        ),
        migrations.AlterModelOptions(
            name='edaralar',
            options={'verbose_name_plural': 'Edaralar'},
        ),
        migrations.AlterModelOptions(
            name='ulanyjy',
            options={'verbose_name_plural': 'Ulanyjylar'},
        ),
        migrations.AddField(
            model_name='bolumler',
            name='edarasy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dolanysygy.Edaralar'),
        ),
        migrations.AddField(
            model_name='bolumler',
            name='welayaty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dolanysygy.Welayatlar'),
        ),
    ]
