# Generated by Django 2.2 on 2019-12-21 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dolanysygy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulanyjy',
            name='ady',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ulanyjy',
            name='bölümi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dolanysygy.Bolumler'),
        ),
        migrations.AlterField(
            model_name='ulanyjy',
            name='edarasy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dolanysygy.Edaralar'),
        ),
        migrations.AlterField(
            model_name='ulanyjy',
            name='mac_adresi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ulanyjy',
            name='welaýaty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dolanysygy.Welayatlar'),
        ),
    ]
