# Generated by Django 2.1 on 2019-12-20 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dolanysygy', '0002_auto_20191220_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady', models.CharField(max_length=200)),
                ('dokement', models.FileField(upload_to='Dokumentler')),
                ('döredilen_senesi', models.DateTimeField(auto_now=True)),
                ('üýgedilen_senesi', models.DateTimeField(auto_now_add=True)),
                ('ulanyjy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Faýl',
            },
        ),
        migrations.CreateModel(
            name='Hasabat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady', models.CharField(max_length=200)),
                ('bolumi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dolanysygy.Bolumler')),
            ],
            options={
                'verbose_name_plural': 'Hasabat',
            },
        ),
    ]
